/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_estyle_myapplication321c_User */

#ifndef _Included_com_example_estyle_myapplication321c_User
#define _Included_com_example_estyle_myapplication321c_User
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
